kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-iad
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  serviceSubnet: "10.21.0.0/16"
  podSubnet: "10.20.0.0/16"
