service:
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: local
pgEdge:
  appName: pgedge-iad
  initSpock: false
  provisionCerts: true
  nodes:
    - name: n1
      hostname: pgedge-iad-n1-rw.default.svc.clusterset.local
    - name: n2
      hostname: pgedge-iad-n2-rw.default.svc.clusterset.local
  externalNodes:
    - name: n3
      hostname: pgedge-sfo-n3-rw.default.svc.clusterset.local
    - name: n4
      hostname: pgedge-sfo-n4-rw.default.svc.clusterset.local
  clusterSpec:
    storage:
      size: 1Gi
