pgEdge:
  appName: pgedge-iad
  initSpock: false
  provisionCerts: true
  nodes:
    - name: n1
      hostname: pgedge-iad-n1-rw-global.default.svc.clusterset.local
      clusterSpec:
        managed:
          services:
            additional:
              - selectorType: rw 
                serviceTemplate:
                  metadata:
                    name: pgedge-iad-n1-rw-global
                    annotations:
                      service.cilium.io/global: "true"
                      service.cilium.io/affinity: "local"
                  spec:
                    type: ClusterIP
                    ports:
                      - name: postgres
                        port: 5432
                        targetPort: 5432
    - name: n2
      hostname: pgedge-iad-n2-rw-global.default.svc.clusterset.local
      clusterSpec:
        managed:
          services:
            additional:
              - selectorType: rw 
                serviceTemplate:
                  metadata:
                    name: pgedge-iad-n2-rw-global
                    annotations:
                      service.cilium.io/global: "true"
                      service.cilium.io/affinity: "local"
                  spec:
                    type: ClusterIP
                    ports:
                      - name: postgres
                        port: 5432
                        targetPort: 5432
  externalNodes:
    - name: n3
      hostname: pgedge-sfo-n3-rw-global.default.svc.clusterset.local
    - name: n4
      hostname: pgedge-sfo-n4-rw-global.default.svc.clusterset.local
  clusterSpec:
    storage:
      size: 1Gi
