kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-sfo
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  serviceSubnet: "10.31.0.0/16"
  podSubnet: "10.30.0.0/16"
