# This configuration is adapted from CloudNativePG documentation:
# https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-example-cert-manager.yaml
#
# Original work # Copyright (c) contributors to CloudNativePG, established as
# CloudNativePG a Series of LF Projects, LLC.
# Licensed under the Creative Commons Attribution 4.0 International License (CC BY 4.0):
# https://creativecommons.org/licenses/by/4.0/
#
# Modifications for pgEdge:
# Copyright (c) 2023 - 2025, pgEdge, Inc.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement is
# hereby granted, provided that the above copyright notice and this paragraph and
# the following two paragraphs appear in all copies.
#
# IN NO EVENT SHALL pgEdge, Inc. BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,
# SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING
# OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF pgEdge, Inc. HAS
# BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# pgEdge, Inc. SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND pgEdge,
# Inc. HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS,
# OR MODIFICATIONS.
#
# Modifications: updated comments and values to align with pgEdge example usage.

{{- if .Values.pgEdge.provisionCerts }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.pgEdge.appName }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pgEdge.appName }}-client-ca
spec:
  isCA: true
  commonName: my-selfsigned-client-ca
  secretName: {{ .Values.pgEdge.appName }}-client-ca-key-pair
  privateKey:
    rotationPolicy: Never
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.pgEdge.appName }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.pgEdge.appName }}-client-ca-issuer
spec:
  ca:
    secretName: {{ .Values.pgEdge.appName }}-client-ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgEdge.appName }}-streaming-replica-client-cert
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pgEdge.appName }}-streaming-replica-client-cert
spec:
  secretName: {{ .Values.pgEdge.appName }}-streaming-replica-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: {{ .Values.pgEdge.appName }}-client-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pgEdge.appName }}-pgedge-client-cert
spec:
  secretName: {{ .Values.pgEdge.appName }}-pgedge-client-cert
  usages:
    - client auth
  commonName: pgedge
  issuerRef:
    name: {{ .Values.pgEdge.appName }}-client-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pgEdge.appName }}-admin-client-cert
spec:
  secretName: {{ .Values.pgEdge.appName }}-admin-client-cert
  usages:
    - client auth
  commonName: admin
  issuerRef:
    name: {{ .Values.pgEdge.appName }}-client-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.pgEdge.appName }}-app-client-cert
spec:
  secretName: {{ .Values.pgEdge.appName }}-app-client-cert
  usages:
    - client auth
  commonName: app
  issuerRef:
    name: {{ .Values.pgEdge.appName }}-client-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never
{{- end }}