---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgedge.v0.dbJsonName" $ }}
  {{- if .Values.labels }}
  labels:
    {{- .Values.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
data:
  db.json: |
    {{ include "pgedge.v0.dbSpec" $ }}
