{{- if .Values.pgEdge.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.pgEdge.appName }}
  labels: {{- include "pgedge.v0.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pgEdge.pdb.minAvailable }}
  minAvailable: {{ .Values.pgEdge.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pgEdge.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pgEdge.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "pgedge.v0.matchLabels" . | nindent 6 }}
{{- end }}
