apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Values.pgEdge.appName }}
data:
  pgedge.json: |-
    [
    {{- $allNodes := concat .Values.pgEdge.nodes .Values.pgEdge.externalNodes }}
    {{- range $i, $n := $allNodes }}
      {{- if $i}},{{ end }}
      {
        "name": "{{ $n.name }}",
        "hostname": "{{ $n.hostname }}"
      }
    {{- end }}
    ]
