{{- if not .Values.pgEdge.existingUsersSecret }}
{{- $secretName := include "pgedge.v0.usersSecret" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $secretData := include "pgedge.v0.dbSpec.users" . | b64enc -}}
{{- if $secret -}}
{{- $secretData = index $secret.data "users.json" }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "pgedge.v0.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
data:
  users.json: |
    {{ $secretData }}
{{- end }}
