{{- if not .Values.pgEdge.existingUsersSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgedge.v0.usersSecret" $ }}
  {{- if .Values.labels }}
  labels:
    {{- .Values.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
data:
  users.json: |
    {{ include "pgedge.v0.dbSpec.users" $ | b64enc }}
{{- end }}
