---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgedge.v0.headlessSvcName" $ }}
  labels:
    app: {{ .Values.pgEdge.appName }}
    {{- if .Values.labels }}
    {{- .Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.pgEdge.port }}
    name: postgres
  clusterIP: None
  selector:
    app: {{ .Values.pgEdge.appName }}
