---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgedge.v0.headlessSvcName" . }}
  labels: {{- include "pgedge.v0.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.pgEdge.port }}
    name: postgres
  clusterIP: None
  selector: {{- include "pgedge.v0.matchLabels" . | nindent 4 }}
