---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgedge.v0.svcName" $ }}
  {{- if .Values.labels }}
  labels:
    {{- .Values.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if or .Values.annotations .Values.service.annotations }}
  annotations:
    {{- if .Values.annotations }}
    {{- .Values.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- .Values.service.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges | toJson}}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- .Values.service.sessionAffinityConfig | toYaml | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Values.pgEdge.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.pgEdge.port }}
      targetPort: {{ .Values.pgEdge.port }}
