apiVersion: v1
kind: Pod
metadata:
  name: ace
spec:
  restartPolicy: Never
  initContainers:
    - name: merge-files
      image: alpine:latest
      command:
        - /bin/sh
        - -c
        - |
          # Merge db.json (from ConfigMap) and users.json (from Secret)
          apk add --no-cache jq && \
          jq -s 'add' /mnt/config/db.json /mnt/secret/users.json > /mnt/merged/db.json
      volumeMounts:
        - name: config-volume
          mountPath: /mnt/config 
        - name: secret-volume
          mountPath: /mnt/secret
        - name: merged-volume
          mountPath: /mnt/merged 
  containers:
    - name: ace
      image: pgedge/ace:latest
      volumeMounts:
        - name: merged-volume
          mountPath: /home/pgedge
  volumes:
    - name: config-volume
      configMap:
        name: pgedge-dbjson
    - name: secret-volume
      secret:
        secretName: pgedge-users
    - name: merged-volume
      emptyDir: {} 